services:

  solr-init:
    image: solr:9.4.1
    container_name: 2025solrInit
    user: root
    volumes:
      - solr_data:/var/solr
    configs:
      - source: solr-config
        target: /opt/solr-config/solr.xml
      - source: solr-security
        target: /opt/solr-config/security.json
    entrypoint:
      - bash
      - -c
      - |
        cp /opt/solr-config/solr.xml /var/solr/data/solr.xml
        cp /opt/solr-config/security.json /var/solr/data/security.json
        chown -R solr:solr /var/solr

  solr:
    image: solr:9.4.1
    container_name: 2025solr
    depends_on:
      - solr-init
    ports:
     - "8986:8983"
    user: solr
    volumes:
      - solr_data:/var/solr
    command:
        - solr-precreate
        - core0
        - solr-precreate
        - core1
        - solr-precreate
        - core2
    environment: # this shouldnt work with security file present (for testing)
      - SOLR_AUTH_TYPE=basic
      - SOLR_AUTHENTICATION_OPTS=-Dbasicauth=admin:admin123

  solr-loader: #script that loads example data, not for use in production
    image: solr:9.4.1
    container_name: 2025solrLoaderPleaseDispose
    profiles: ["loader"]
    depends_on:
      - solr
    entrypoint:
      - sh
      - -c
      - | #health check would be better than sleep
        sleep 10 && \
        curl -o /tmp/books.csv https://raw.githubusercontent.com/apache/solr/main/solr/example/exampledocs/books.csv && \
        curl -u solr:SolrRocks -X POST -H "Content-Type: application/csv" \
          --data-binary @/tmp/books.csv \
          "http://solr:8983/solr/core2/update?commit=true"

  dozzle:
    image: amir20/dozzle:latest
    container_name: 2025dozzle
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  solr_data:

configs:
  solr-config:
    file: ./files/solr.xml
  solr-security:
    file: ./files/security.json
