services:

  solr:
    image: solr:9.4.1
    container_name: 2025solr
    ports:
     - "8986:8983"
    volumes:
      - solr_data:/var/solr
    configs:
    # this could cause issues with write permissions, its better to mount them somewhere else -> then copy them
      - source: solr-config
        target: /var/solr/data/solr.xml
      - source: solr-security
        target: /var/solr/data/security.json
    command:
        - solr-precreate
        - core0
        - solr-precreate
        - core1
        - solr-precreate
        - core2
    environment: # this shouldnt work with security file present (for testing)
      - SOLR_AUTH_TYPE=basic
      - SOLR_AUTHENTICATION_OPTS=-Dbasicauth=admin:admin123


  dozzle:
    image: amir20/dozzle:latest
    container_name: 2025dozzle
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  solr_data:

configs:
  solr-config:
    file: ./files/solr.xml
  solr-security:
    file: ./files/security.json